# Generated by Django 5.1.7 on 2025-09-27 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatting', '0001_initial'),
        ('budget_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='chat',
            name='edit_history',
            field=models.JSONField(blank=True, default=list, help_text='List of previous versions with timestamps'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='original_message',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['timestamp'], name='Chatting_ch_timesta_23c930_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user_from', 'user_to'], name='Chatting_ch_user_fr_7a552f_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['transaction'], name='Chatting_ch_transac_afde85_idx'),
        ),
    ]
