# Generated by Django 5.1.7 on 2025-09-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatting', '0002_alter_chat_options_chat_edit_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='seen',
            field=models.BooleanField(default=False, help_text='Whether the message has been seen by the recipient'),
        ),
        migrations.AddField(
            model_name='chat',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
