# Generated by Django 5.1.7 on 2025-09-08 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='xx_TransactionTransfer',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('approved_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('available_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('from_center', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('to_center', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('account_code', models.IntegerField(blank=True, null=True)),
                ('account_name', models.TextField(blank=True, null=True)),
                ('project_code', models.IntegerField(blank=True, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('cost_center_code', models.IntegerField(blank=True, null=True)),
                ('cost_center_name', models.TextField(blank=True, null=True)),
                ('done', models.IntegerField(default=1)),
                ('encumbrance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='adjd_transfers/')),
                ('transaction', models.ForeignKey(blank=True, db_column='transaction_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjd_transfers', to='budget_management.xx_budgettransfer')),
            ],
            options={
                'db_table': 'XX_TRANSACTION_TRANSFER_XX',
            },
        ),
    ]
