# Generated by Django 5.1.7 on 2025-09-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XX_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_default', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'XX_ACCOUNT_XX',
            },
        ),
        migrations.CreateModel(
            name='XX_Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_default', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'XX_ENTITY_XX',
            },
        ),
        migrations.CreateModel(
            name='XX_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_default', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'XX_PROJECT_XX',
            },
        ),
        migrations.CreateModel(
            name='XX_TransactionAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_id', models.IntegerField(blank=True, null=True)),
                ('transcation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_center_code', models.CharField(blank=True, max_length=50, null=True)),
                ('account_code', models.CharField(blank=True, max_length=50, null=True)),
                ('project_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'XX_TRANSACTION_AUDIT_XX',
            },
        ),
        migrations.CreateModel(
            name='XX_ACCOUNT_ENTITY_LIMIT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_transer_allowed_for_source', models.CharField(blank=True, max_length=255, null=True)),
                ('is_transer_allowed_for_target', models.CharField(blank=True, max_length=255, null=True)),
                ('is_transer_allowed', models.CharField(blank=True, max_length=255, null=True)),
                ('source_count', models.IntegerField(blank=True, null=True)),
                ('target_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'XX_ACCOUNT_ENTITY_LIMIT_XX',
                'unique_together': {('account_id', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='XX_PivotFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField()),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('fund', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('encumbrance', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'db_table': 'XX_PIVOTFUND_XX',
                'constraints': [models.UniqueConstraint(fields=('entity', 'account', 'project', 'year'), name='unique_entity_account_year')],
            },
        ),
    ]
