# Generated by Django 4.2.7 on 2025-09-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XX_BalanceReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('control_budget_name', models.CharField(blank=True, help_text='Control Budget Name', max_length=100, null=True)),
                ('ledger_name', models.CharField(blank=True, help_text='Ledger Name', max_length=100, null=True)),
                ('as_of_period', models.CharField(blank=True, help_text='As of Period (e.g., Sep-25)', max_length=20, null=True)),
                ('segment1', models.CharField(blank=True, help_text='Segment 1 (Cost Center)', max_length=50, null=True)),
                ('segment2', models.CharField(blank=True, help_text='Segment 2 (Account)', max_length=50, null=True)),
                ('segment3', models.CharField(blank=True, help_text='Segment 3 (Project)', max_length=50, null=True)),
                ('encumbrance_ytd', models.DecimalField(blank=True, decimal_places=2, help_text='Encumbrance Year to Date', max_digits=20, null=True)),
                ('other_ytd', models.DecimalField(blank=True, decimal_places=2, help_text='Other Year to Date', max_digits=20, null=True)),
                ('actual_ytd', models.DecimalField(blank=True, decimal_places=2, help_text='Actual Year to Date', max_digits=20, null=True)),
                ('funds_available_asof', models.DecimalField(blank=True, decimal_places=2, help_text='Funds Available As Of', max_digits=20, null=True)),
                ('budget_ytd', models.DecimalField(blank=True, decimal_places=2, help_text='Budget Year to Date', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Balance Report',
                'verbose_name_plural': 'Balance Reports',
                'db_table': 'XX_BALANCE_REPORT_XX',
                'indexes': [models.Index(fields=['control_budget_name', 'as_of_period'], name='XX_BALANCE__control_ba7cc4_idx'), models.Index(fields=['segment1', 'segment2', 'segment3'], name='XX_BALANCE__segment_8c711d_idx'), models.Index(fields=['as_of_period'], name='XX_BALANCE__as_of_p_67c5e2_idx')],
            },
        ),
    ]
