# Generated by Django 5.2.1 on 2025-09-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0002_xx_balancereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('envelope', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'db_table': 'XX_PROJECT_ENVELOPE_XX',
            },
        ),
    ]
