# Generated by Django 5.2.1 on 2025-09-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0003_envelopemanager_project_envelope'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvelopeManager',
        ),
    ]
