# Generated by Django 5.2.5 on 2025-09-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0004_delete_envelopemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='XX_ACCOUNT_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_account', models.CharField(max_length=50)),
                ('target_account', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'XX_ACCOUNT_MAPPING_XX',
                'unique_together': {('source_account', 'target_account')},
            },
        ),
        migrations.CreateModel(
            name='XX_Entity_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_entity', models.CharField(max_length=50)),
                ('target_entity', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'XX_ENTITY_MAPPING_XX',
                'unique_together': {('source_entity', 'target_entity')},
            },
        ),
    ]
