# Generated by Django 5.1.7 on 2025-09-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0005_xx_account_mapping_xx_entity_mapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XX_ACCOUNT_mapping',
        ),
        migrations.DeleteModel(
            name='XX_Entity_mapping',
        ),
    ]
