# Generated by Django 5.1.7 on 2025-09-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0006_delete_xx_account_mapping_delete_xx_entity_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_account', models.CharField(max_length=50)),
                ('target_account', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'XX_ACCOUNT_MAPPING_XX',
                'unique_together': {('source_account', 'target_account')},
            },
        ),
    ]
