# Generated by Django 5.1.7 on 2025-09-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0007_account_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('FY24_budget', models.DecimalField(decimal_places=2, max_digits=30)),
                ('FY25_budget', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'db_table': 'BUDGET_DATA_XX',
                'unique_together': {('project', 'account')},
            },
        ),
    ]
