# Generated by Django 4.2.7 on 2025-09-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0008_budget_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account_mapping',
            table='XX_ACCOUNT_MAPPING_LEGACY_XX',
        ),
        migrations.CreateModel(
            name='XX_Entity_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_entity', models.CharField(max_length=50)),
                ('target_entity', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'XX_ENTITY_MAPPING__elies_XX',
                'unique_together': {('source_entity', 'target_entity')},
            },
        ),
        migrations.CreateModel(
            name='XX_ACCOUNT_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_account', models.CharField(max_length=50)),
                ('target_account', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'XX_ACCOUNT_MAPPING__elies_XX',
                'unique_together': {('source_account', 'target_account')},
            },
        ),
    ]
