# Generated by Django 5.2.1 on 2025-09-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalaction',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('delegate', 'Delegate')], max_length=10),
        ),
    ]
