# Generated by Django 5.2.5 on 2025-10-10 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='xx_Invoice',
            fields=[
                ('Invoice_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Invoice_Number', models.CharField(max_length=100, unique=True)),
                ('Invoice_Data', models.JSONField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'XX_INVOICE_XX',
            },
        ),
    ]
