# Generated by Django 5.2.5 on 2025-10-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_invoice',
            name='base64_file',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='xx_invoice',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
