# Generated by Django 5.2.5 on 2025-10-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0002_xx_invoice_base64_file_xx_invoice_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_invoice',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
