# Generated by Django 5.2.5 on 2025-10-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0003_xx_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_invoice',
            name='code_combination',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='xx_invoice',
            name='code_description',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
    ]
