# Generated by Django 5.2.5 on 2025-10-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0004_xx_invoice_code_combination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xx_invoice',
            name='code_combination',
        ),
        migrations.RemoveField(
            model_name='xx_invoice',
            name='code_description',
        ),
    ]
